import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button } from 'shared/components/atoms'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://rickandmortyapi.com">Rick&Morty's</a> searcher
        </h1>

        <Image alt="logo" id="logo" width="500px" height="300px" src="/Logo.svg" />
        <Button onClick={() => {}}>LogIn to start searching</Button>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/gagocarrilledgar" target="_blank" rel="noopener noreferrer">
          Developed with 💚 from BCN
        </a>
      </footer>
    </div>
  )
}

export default Home
